#!/bin/bash

# How to use:
# (./loop_sq_po.sh 2>&1) | tee loop_sq_po.output
#
# 1) The function gen_tests generates a list of tests to the file TEST_LIST 
#    i.e. loop_sq_po.testlist
#
# 2) The function run_tests will read in each test from loop_sq_po.testlist
#    and run them.
#   
#   List of files:
#
#   loop_sq_po.sh: this current run script.
#   loop_sq_po.output: output from this run script. If any test fails, we can see them here.
#   loop_sq_po.testlist: All the tests to run. This is generated by the function gen_tests
#   loop_sq_po.testoutput: the stdout from all the tests.
#   ./res_sq_po/ the results I'm interested. (This is set within the program)
#
#   In case we need to re-run some tests if they fail, or if we need to stop the
#   script at any point. We simply find which test it is currently doing in loop_sq_po.testlist
#   and start from there.

# SET THIS.
PROGRAM="sq_van"

FILE=$0 # This contains "./", which we do not want.
FILE=${FILE:2} # Gets rid of "./"
FILEBASE=${FILE%%.*} # Get rid of the extension (in this case, ".sh")
CURRENTDIR=`pwd`
OOMPHROOT=$(make -s --no-print-directory print-top_builddir)

ITSTIMEDIR="res_$FILEBASE"
TESTLIST_FILE="$ITSTIMEDIR/$FILEBASE.testlist"
TESTOUT_FILE="$ITSTIMEDIR/$FILEBASE.testoutput"

gen_tests()
{
#PRECLIST="0 1 2" # Doing either full exact or Exact Navier Stokes
# 0 - W SuperLU, NS SuperLU
# 1 - W SuperLU, NS LSC: P SuperLU, F SuperLU
# 2 - W SuperLU, NS LSC: P AMG, F AMG

PRECLIST="0 1 2"
# The precs are set according to the PRECLIST above.
NSPRECLIST="0" # 0 - Exact, 1 - LSC
PPRECLIST="0" # Only for LSC, 0 - Exact, 1 - AMG
FPRECLIST="0" # Only for LSC, 0 - Exact, 1 - AMG

VISLIST="0 1"
ANGLIST="0"
RELIST="0 100 200"
NOELLIST="4 8 16 32 64 128 256"

for PREC  in $PRECLIST
do
  case "$PREC" in
    0)
    NSPRECLIST="0"
    ;;
    1)
    NSPRECLIST="1"
    PPRECLIST="0"
    FPRECLIST="0"
    ;;
    2)
    NSPRECLIST="1"
    PPRECLIST="1"
    FPRECLIST="1"
    ;;
    esac
  for NSPREC in $NSPRECLIST
  do
    if [ $NSPREC == 1 ]; then
      for PPREC in $PPRECLIST 
      do
        for FPREC in $FPRECLIST 
        do
          for VIS in $VISLIST
          do
            for ANG in $ANGLIST
            do
              for RE in $RELIST
              do
                for NOEL in $NOELLIST
                do
echo "mpirun -np 1 ./$PROGRAM --ns_solver $NSPREC --p_solver $PPREC --f_solver $FPREC --visc $VIS --ang $ANG --rey $RE --noel $NOEL --itstimedir $ITSTIMEDIR" >> $TESTLIST_FILE
                done
              done
            done
          done
        done
      done
    else
      for VIS in $VISLIST 
      do
        for ANG in $ANGLIST
        do
          for RE in $RELIST
          do
            for NOEL in $NOELLIST
            do
echo "mpirun -np 1 ./$PROGRAM --ns_solver $NSPREC --visc $VIS --ang $ANG --rey $RE --noel $NOEL --itstimedir $ITSTIMEDIR" >> $TESTLIST_FILE
            done
          done
        done
      done
    fi
  done
done

} # gen_tests function

run_tests()
{
  while read RUNCOMMAND; do
    echo "Doing $RUNCOMMAND on $(date)"
    bash -c "$RUNCOMMAND" </dev/null >> $TESTOUT_FILE
  done < $TESTLIST_FILE
}

#cd $OOMPHTOPDIR/src/ && make && make install && \
#cd $CURRENTDIR && make $PROGRAM && \
make $PROGRAM &&
rm -rf $ITSTIMEDIR && mkdir $ITSTIMEDIR &&
gen_tests && run_tests

