#!/bin/bash

# How to use:
# (./loop_sq_po.sh 2>&1) | tee loop_sq_po.output
#
# 1) The function gen_tests generates a list of tests to the file TEST_LIST 
#    i.e. loop_sq_po.testlist
#
# 2) The function run_tests will read in each test from loop_sq_po.testlist
#    and run them.
#   
#   List of files:
#
#   loop_sq_po.sh: this current run script.
#   loop_sq_po.output: output from this run script. If any test fails, we can see them here.
#   loop_sq_po.testlist: All the tests to run. This is generated by the function gen_tests
#   loop_sq_po.testoutput: the stdout from all the tests.
#   ./res_sq_po/ the results I'm interested. (This is set within the program)
#
#   In case we need to re-run some tests if they fail, or if we need to stop the
#   script at any point. We simply find which test it is currently doing in loop_sq_po.testlist
#   and start from there.

FILE=$0 # This contains "./", which we do not want.
FILE=${FILE:2} # Gets rid of "./"
FILEBASE=${FILE%%_catres.*} # Get rid of the extension (in this case, ".sh")

ITSTIMEDIR="res_$FILEBASE"
TESTLIST_FILE="$ITSTIMEDIR/$FILEBASE.testlist"
TESTOUT_FILE="$ITSTIMEDIR/$FILEBASE.testoutput"

gen_tests()
{
#PRECLIST="0 1 2" # Doing either full exact or Exact Navier Stokes
# 0 - W SuperLU, NS SuperLU
# 1 - W SuperLU, NS LSC: P SuperLU, F SuperLU
# 2 - W SuperLU, NS LSC: P AMG, F AMG

PROBNAME="SqcVan"
PRECLIST="Ne NlFePe NlFaPa"

VISLIST="Sim Str"
ANGLIST="A0"
RELIST="R0 R100 R200"
NOELLIST="N4 N8 N16 N32 N64 N128 N256"

for PREC  in $PRECLIST
do
  for VIS in $VISLIST
  do
    for ANG in $ANGLIST
    do
      for RE in $RELIST
      do
        for NOEL in $NOELLIST
        do
          RESFILE="./${ITSTIMEDIR}/${PROBNAME}${PREC}${VIS}${ANG}${RE}${NOEL}"
          if [ ! -f $RESFILE ]; then
            echo "$RESFILE NOTFOUND"
          else
            cat $RESFILE
          fi
        done
      done
    done
  done
done


} # gen_tests function

gen_tests

